kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dmn-svc-notation-bc
  labels:
    app: dmn-svc-notation
    app.kubernetes.io/component: dmn-svc-notation
    app.kubernetes.io/instance: dmn-svc-notation
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: dmn-svc-notation-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: '8'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'dmn-svc-notation:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  source:
      binary: {}
      type: Binary
  strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
