apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dmn-svc-bc
metadata:
  annotations:
    description: Template to build application with DMN service
    iconClass: icon-rh-integration
    openshift.io/display-name: DMN Credit Scoring SVC 
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: quarkus,java,kogito,springboot,dmn
    version: "1.1"
  name: dmn-svc-bc
objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: dmn-svc-notation-bc
      labels:
        app: dmn-svc-notation
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'dmn-svc-notation:latest'
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      source:
          binary: {}
          type: Binary
      strategy:
          sourceStrategy:
            from:
              kind: ImageStreamTag
              name: redhat-openjdk18-openshift:1.2
              namespace: openshift
          type: Source
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
